name: PR Build Test

on:
  pull_request:
    branches: [main]

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: ./.github/actions/build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Annotate Lint
        uses: ./.github/actions/annotate-lint
      - name: Lint
        uses: ./.github/actions/lint
